# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sbanks
                                 A QGIS plugin
 Don't Zig. Unzag
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-16
        copyright            : (C) 2026 by Anatoly Tsyplenkov
        email                : hard.sign9115@fastmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Anatoly Tsyplenkov"
__date__ = "2026-01-16"
__copyright__ = "(C) 2026 by Anatoly Tsyplenkov"

import os
import sys

# Patch sys.path to include vendor/sbanks-lib for sbanks_core imports
_current_dir = os.path.dirname(os.path.abspath(__file__))
_vendor_dir = os.path.join(_current_dir, "vendor", "sbanks-lib")
if _vendor_dir not in sys.path:
    sys.path.insert(0, _vendor_dir)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sbanks class from file Sbanks.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .sbanks_plugin import SbanksPlugin

    return SbanksPlugin()
