# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Sbanks
                                 A QGIS plugin
 Don't Zig. Unzag
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-16
        copyright            : (C) 2026 by Anatoly Tsyplenkov
        email                : atsyplenkov@geogr.msu.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Anatoly Tsyplenkov'
__date__ = '2026-01-16'
__copyright__ = '(C) 2026 by Anatoly Tsyplenkov'

__revision__ = '$Format:%H$'

from qgis.core import QgsApplication
from .sbanks_provider import SbanksProvider


class SbanksPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = SbanksProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
