# -*- coding: utf-8 -*-

"""
/***************************************************************************
 sbanks
                                 A QGIS plugin
 Don't Zig. Unzag
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-16
        copyright            : (C) 2026 by Anatoly Tsyplenkov
        email                : hard.sign9115@fastmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Anatoly Tsyplenkov"
__date__ = "2026-01-16"
__copyright__ = "(C) 2026 by Anatoly Tsyplenkov"

__revision__ = "$Format:%H$"

import os

from qgis.core import QgsApplication
from qgis.PyQt.QtCore import QCoreApplication, QLocale, QSettings, QTranslator

from .sbanks_provider import SbanksProvider


class SbanksPlugin(object):
    def __init__(self):
        self.provider = None
        self.translator = None
        self.plugin_dir = os.path.dirname(__file__)

    def _init_translation(self):
        override_locale = QSettings().value("locale/overrideFlag", False, type=bool)
        if override_locale:
            locale_name = QSettings().value("locale/userLocale", "")
        else:
            locale_name = QLocale.system().name()

        locale_candidates = [locale_name]
        if "_" in locale_name:
            locale_candidates.append(locale_name.split("_", 1)[0])

        for locale in locale_candidates:
            locale_path = os.path.join(
                self.plugin_dir, "i18n", "sbanks_{}.qm".format(locale)
            )
            if os.path.exists(locale_path):
                self.translator = QTranslator()
                self.translator.load(locale_path)
                QCoreApplication.installTranslator(self.translator)
                break

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = SbanksProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self._init_translation()
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        if self.translator is not None:
            QCoreApplication.removeTranslator(self.translator)
            self.translator = None
